name: Release and deploy PREPROD

on:
  push:
    branches:
      - "main"

jobs:
  preprod-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Build docker image
        run: |
          gradle build
          docker build \
          -t ${{ secrets.DOCKER_IMAGE_NAME }}:preprod-latest \
          -t ${{ secrets.DOCKER_IMAGE_NAME }}:preprod-${GITHUB_SHA::7} .
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image
        run: docker push -a ${{ secrets.DOCKER_IMAGE_NAME }}

  deploy-to-preprod:
    needs: preprod-release
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook request
        run: "curl -X POST ${{ secrets.WEBHOOK_URL_PREPROD }}"
