name: CI for push

on:
  push:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Building and testing
        run: gradle test

  build-docker-image:
    runs-on: ubuntu-latest
    needs: run-unit-tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Build docker image
        run: |
          gradle build
          docker build \
          -t ${{ secrets.DOCKER_IMAGE_NAME }}:rc-latest \
          -t ${{ secrets.DOCKER_IMAGE_NAME }}:${GITHUB_SHA::7} .
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image
        run: docker push -a ${{ secrets.DOCKER_IMAGE_NAME }}
